websites:
  thiessen.com.mx:
    url: https://thiessen.com.mx
    search_path: /properties-search/page/PAGE_NUMBER/
    results_per_page: 6
    queries:
      listing_type:
        - bodega
        - shop
        - office
        - otro
        - single-family
        - casa-bodega
        - apartment
        - lote
        - rancho
      sortby: date-desc
